### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by skbrown333** [CookbookGG/web#20]
- [ ] Adding new posts 🙃 
- [ ] Drag and drop folders / sections
- [ ] rename folders / sections
- [ ] cookbook home section
- [ ] Cookbook.gg landing page w/ featured guides
- [ ] section authors
- [ ] unify edit / clean up save cancel buttons
